name: Test

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11"]
  steps:
  - uses: actions/checkout@v4
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.x'
  - name: Install dependencies
    run: python -m pip install --upgrade pip setuptools pytest
  - name: Install package
    run: pip install working/rodolfosgameoflife
  - name: Test with pytest
    run: pytest working/rodolfosgameoflife/test --junitxml=junit/test-results.xml
  - name: Upload pytest test results
    uses: actions/upload-artifact@v3
    with:
      name: pytest-results-${{ matrix.python-version }}
      path: junit/test-results-${{ matrix.python-version }}.xml
    if: ${{ always() }}

